import type { QualityStatus, SourceReference, SourcedValue, ValidatedSubstanceRecord } from './validatedSubstanceTypes';

const VERIFIED_AT = '2026-09-14';
const field = <T>(value: T | null, sourceIds: readonly string[], status: QualityStatus = 'verified'): SourcedValue<T> => ({ value, sourceIds, status, verifiedAt: VERIFIED_AT });

const ADR: SourceReference = { id: 'adr-2025', title: 'ДОПОГ 2025, таблица A главы 3.2', organization: 'ЕЭК ООН', url: 'https://unece.org/transport/dangerous-goods/adr-2025-files', edition: 'ADR 2025', accessedAt: VERIFIED_AT, purpose: 'transport' };
const RAIL: SourceReference = { id: 'rail-cards-2026', title: 'Аварийные карточки на опасные грузы, перевозимые по железным дорогам', organization: 'Министерство транспорта Российской Федерации', url: 'https://www.mintrans.gov.ru/documents/6/825', edition: 'Редакция базы 2026.01', accessedAt: VERIFIED_AT, purpose: 'rail-emergency' };
const ICSC_CHLORINE: SourceReference = { id: 'icsc-0126', title: 'ICSC 0126 — Chlorine', organization: 'МОТ / ВОЗ', url: 'https://chemicalsafety.ilo.org/dyn/icsc/showcard.display?p_card_id=0126&p_lang=en&p_version=1', edition: 'March 2009', accessedAt: VERIFIED_AT, purpose: 'individual-profile' };
const ICSC_AMMONIA: SourceReference = { id: 'icsc-0414', title: 'ICSC 0414 — Ammonia (anhydrous)', organization: 'МОТ / ВОЗ', url: 'https://chemicalsafety.ilo.org/dyn/icsc/showcard.display?p_card_id=0414&p_lang=en&p_version=1', edition: 'October 2013', accessedAt: VERIFIED_AT, purpose: 'individual-profile' };
const ICSC_HCL: SourceReference = { id: 'icsc-0163', title: 'ICSC 0163 — Hydrogen chloride', organization: 'МОТ / ВОЗ', url: 'https://chemicalsafety.ilo.org/dyn/icsc/showcard.display?p_card_id=0163&p_lang=en&p_version=1', edition: 'November 2016', accessedAt: VERIFIED_AT, purpose: 'individual-profile' };
const ICSC_NAOH: SourceReference = { id: 'icsc-0360', title: 'ICSC 0360 — Sodium hydroxide', organization: 'МОТ / ВОЗ', url: 'https://chemicalsafety.ilo.org/dyn/icsc/showcard.display?p_card_id=0360&p_lang=en&p_version=1', edition: 'May 2010', accessedAt: VERIFIED_AT, purpose: 'individual-profile' };
const ICSC_METHANE: SourceReference = { id: 'icsc-0291', title: 'ICSC 0291 — Methane', organization: 'МОТ / ВОЗ', url: 'https://chemicalsafety.ilo.org/dyn/icsc/showcard.display?p_card_id=0291&p_lang=en&p_version=1', edition: 'February 2000', accessedAt: VERIFIED_AT, purpose: 'individual-profile' };
const RPOHV_CHLORINE: SourceReference = { id: 'rpohv-chlorine', title: 'Федеральный регистр — Хлор, АТ-000138', organization: 'Роспотребнадзор', url: 'https://www.rpohv.ru/online/detail.html?id=138', edition: 'Онлайн-карта вещества', accessedAt: VERIFIED_AT, purpose: 'identity' };
const RPOHV_AMMONIA: SourceReference = { id: 'rpohv-ammonia', title: 'Федеральный регистр — Аммиак, АТ-000053', organization: 'Роспотребнадзор', url: 'https://www.rpohv.ru/online/detail.html?id=53', edition: 'Актуализация 29.05.2024', accessedAt: VERIFIED_AT, purpose: 'identity' };
const RPOHV_NAOH: SourceReference = { id: 'rpohv-naoh', title: 'Федеральный регистр — Натрий гидроксид, АТ-000137', organization: 'Роспотребнадзор', url: 'https://www.rpohv.ru/online/detail.html?id=137', edition: 'Онлайн-карта вещества', accessedAt: VERIFIED_AT, purpose: 'identity' };

type PilotOptions = Readonly<{
  un: string; recordId: string; name: string; chemicalName: string; cas: string; formula: string; aliases: readonly string[]; physicalForm: string; concentration: string;
  isAnhydrous?: boolean; isSolution?: boolean; isRefrigeratedLiquid?: boolean; className: string; code: string; kemler: string; packingGroup: string; labels: readonly string[];
  card: string; identitySources: readonly SourceReference[]; profileSource: SourceReference; main: readonly string[]; fire: readonly string[]; health: readonly string[]; routes: readonly string[];
  ppe: readonly string[]; actions: readonly string[]; operation: 'neutralization' | 'containment' | 'absorption' | 'dilution' | 'controlled_dispersion' | 'collection' | 'disposal' | 'no_neutralization'; response: readonly string[]; firstAid: readonly string[];
  flags: ValidatedSubstanceRecord['emergency']['flags'];
}>;

function pilot(options: PilotOptions): ValidatedSubstanceRecord {
  const identitySourceIds = options.identitySources.map((source) => source.id);
  const profileSources = [options.profileSource.id];
  const productFormId = `product-${options.un}`;
  const transportEntryId = `transport-${options.un}`;
  const sources = [...new Map([...options.identitySources, options.profileSource, ADR, RAIL].map((source) => [source.id, source])).values()];
  return {
    schemaVersion: 2, recordId: options.recordId, recordStatus: 'verified',
    chemical: { id: `chemical-${options.cas}`, name: field(options.chemicalName, identitySourceIds), casNumber: field(options.cas, identitySourceIds), formula: field(options.formula, identitySourceIds), synonyms: field(options.aliases, identitySourceIds) },
    productForm: { id: productFormId, chemicalId: `chemical-${options.cas}`, displayName: field(options.name, [ADR.id]), physicalForm: field(options.physicalForm, profileSources), concentration: field(options.concentration, profileSources), isAnhydrous: options.isAnhydrous ?? false, isSolution: options.isSolution ?? false, isRefrigeratedLiquid: options.isRefrigeratedLiquid ?? false },
    transport: { id: transportEntryId, productFormId, unNumber: field(options.un, [ADR.id]), officialTransportName: field(options.name.toUpperCase(), [ADR.id]), hazardClass: field(options.className, [ADR.id]), classificationCode: field(options.code, [ADR.id]), kemlerCode: field(options.kemler, [ADR.id]), packingGroup: field(options.packingGroup, [ADR.id]), hazardLabels: field(options.labels, [ADR.id]), specialProvisions: field([], [ADR.id]) },
    emergency: { productFormId, mainProperties: field(options.main, profileSources), fireExplosionHazards: field(options.fire, profileSources), healthHazards: field(options.health, profileSources), exposureRoutes: field(options.routes, profileSources), ppe: field(options.ppe, profileSources), emergencyActions: field(options.actions, profileSources), consequenceControl: field({ operation: options.operation, actions: options.response }, profileSources), firstAid: field(options.firstAid, profileSources), flags: options.flags },
    transportInstructions: { transportEntryId, road: field([], [ADR.id]), rail: field({ emergencyCardNumber: options.card, cardType: 'group', instructions: [] }, [RAIL.id]) },
    sources, createdAt: VERIFIED_AT, updatedAt: VERIFIED_AT, lastVerifiedAt: VERIFIED_AT, verifiedBy: 'pilot-validator', sourceVersion: 'pilot-2026.09.14', changeReason: 'Разделение индивидуального профиля, транспортной записи и групповой железнодорожной АК.',
  };
}

export const VALIDATED_SUBSTANCES_PILOT: readonly ValidatedSubstanceRecord[] = [
  pilot({ un: '1017', recordId: 'un1017-chlorine-liquefied', name: 'Хлор', chemicalName: 'Хлор', cas: '7782-50-5', formula: 'Cl₂', aliases: ['Хлор жидкий'], physicalForm: 'Сжатый сжиженный газ', concentration: 'Чистое вещество', className: '2.3', code: '2TOC', kemler: '265', packingGroup: '—', labels: ['2.3', '5.1', '8'], card: '203', identitySources: [RPOHV_CHLORINE, ICSC_CHLORINE], profileSource: ICSC_CHLORINE,
    main: ['Зеленовато-жёлтый сжатый сжиженный газ с резким запахом.', 'Газ тяжелее воздуха.', 'Сильный окислитель; раствор в воде является сильной кислотой.'],
    fire: ['Не горит, но усиливает горение других веществ.', 'Многие реакции могут вызвать пожар или взрыв.', 'Нагретый баллон может разрушиться.'],
    health: ['Смертельно опасен при вдыхании.', 'Коррозионен для глаз, кожи и дыхательных путей.', 'Жидкость может вызвать обморожение; возможны пневмонит и отёк лёгких.'], routes: ['вдыхание', 'кожа', 'глаза'],
    ppe: ['Газонепроницаемый костюм химической защиты.', 'Автономный дыхательный аппарат.', 'Защита глаз и холодоизолирующие перчатки.'], actions: ['Эвакуировать опасную зону.', 'Перекрыть выход газа, если это безопасно.', 'Изолировать участок до рассеивания газа.', 'Не направлять струю воды на жидкий хлор.'], operation: 'controlled_dispersion', response: ['Удалять газ мелкодисперсной водяной завесой, не направляя воду на жидкий продукт.', 'Не допускать попадания вещества в окружающую среду.'], firstAid: ['Свежий воздух, покой, полусидячее положение; немедленная медицинская помощь.', 'Кожу промывать водой не менее 15 минут.', 'Глаза промывать водой и немедленно обратиться за медицинской помощью.'], flags: { isCryogenic: false, isToxicGas: true, isCorrosive: true, isOxidizer: true, isFlammable: false, isExplosive: false, isWaterReactive: true, isEnvironmentalHazard: true, isAsphyxiant: false } }),
  pilot({ un: '1005', recordId: 'un1005-ammonia-anhydrous', name: 'Аммиак безводный', chemicalName: 'Аммиак', cas: '7664-41-7', formula: 'NH₃', aliases: ['Аммиак жидкий безводный', 'R717'], physicalForm: 'Газ или сжатый сжиженный газ', concentration: 'Безводный', isAnhydrous: true, className: '2.3', code: '2TC', kemler: '268', packingGroup: '—', labels: ['2.3', '8'], card: '208', identitySources: [RPOHV_AMMONIA, ICSC_AMMONIA], profileSource: ICSC_AMMONIA,
    main: ['Бесцветный газ или сжатый сжиженный газ с резким запахом.', 'Газ легче воздуха.', 'Сильное основание; растворяется в воде с выделением тепла.'], fire: ['Горючий газ; смеси с воздухом взрывоопасны.', 'Баллон может разрушиться при нагревании.', 'Реагирует с кислотами, сильными окислителями и галогенами.'], health: ['Токсичен при вдыхании.', 'Коррозионен для глаз, кожи и дыхательных путей.', 'Быстрое испарение жидкости может вызвать обморожение; возможен отёк лёгких.'], routes: ['вдыхание', 'кожа', 'глаза'], ppe: ['Газонепроницаемый костюм химической защиты.', 'Автономный дыхательный аппарат.', 'Защита глаз и холодоизолирующие перчатки.'], actions: ['Эвакуировать опасную зону.', 'Удалить источники зажигания.', 'Перекрыть выход газа, если это безопасно.', 'Не направлять струю воды на жидкий аммиак.'], operation: 'controlled_dispersion', response: ['Удалять газ мелкодисперсной водяной завесой.', 'Проветривать и изолировать участок до рассеивания газа.'], firstAid: ['Свежий воздух, покой, полусидячее положение; немедленная медицинская помощь.', 'При обморожении промывать водой, не снимать примерзшую одежду.', 'Глаза промывать водой и немедленно обратиться за медицинской помощью.'], flags: { isCryogenic: false, isToxicGas: true, isCorrosive: true, isOxidizer: false, isFlammable: true, isExplosive: true, isWaterReactive: false, isEnvironmentalHazard: true, isAsphyxiant: false } }),
  pilot({ un: '1050', recordId: 'un1050-hydrogen-chloride-anhydrous', name: 'Водорода хлорид безводный', chemicalName: 'Хлороводород', cas: '7647-01-0', formula: 'HCl', aliases: ['Водород хлористый безводный'], physicalForm: 'Бесцветный сжатый сжиженный газ', concentration: 'Безводный', isAnhydrous: true, className: '2.3', code: '2TC', kemler: '268', packingGroup: '—', labels: ['2.3', '8'], card: '203', identitySources: [ICSC_HCL], profileSource: ICSC_HCL,
    main: ['Бесцветный сжатый сжиженный газ с резким запахом.', 'Газ тяжелее воздуха и может скапливаться в понижениях.', 'Раствор в воде является сильной кислотой.'], fire: ['Не горит.', 'Реагирует с основаниями и окислителями.', 'В присутствии воды воздействует на многие металлы с выделением горючего водорода.'], health: ['Коррозионен для глаз, кожи и дыхательных путей.', 'Высокие концентрации могут вызвать пневмонит и отёк лёгких.', 'Жидкость может вызвать обморожение.'], routes: ['вдыхание', 'кожа', 'глаза'], ppe: ['Защитная одежда.', 'Автономный дыхательный аппарат при опасной концентрации.', 'Защита глаз и холодоизолирующие перчатки.'], actions: ['Эвакуировать опасную зону.', 'Перекрыть выход газа, если это безопасно.', 'Изолировать участок до рассеивания газа.'], operation: 'controlled_dispersion', response: ['Обеспечить вентиляцию и контролируемое рассеивание.', 'Не допускать контакта с несовместимыми материалами.'], firstAid: ['Свежий воздух, покой, полусидячее положение; немедленная медицинская помощь.', 'Кожу и глаза промывать водой; при контакте с жидкостью учитывать обморожение.'], flags: { isCryogenic: false, isToxicGas: true, isCorrosive: true, isOxidizer: false, isFlammable: false, isExplosive: false, isWaterReactive: true, isEnvironmentalHazard: false, isAsphyxiant: false } }),
  pilot({ un: '1824', recordId: 'un1824-sodium-hydroxide-solution', name: 'Натрия гидроксида раствор', chemicalName: 'Натрий гидроксид', cas: '1310-73-2', formula: 'NaOH', aliases: ['Натр едкий раствор', 'Каустическая сода, раствор'], physicalForm: 'Водный раствор', concentration: 'Концентрация указывается в перевозочном документе; UN 1824, группа упаковки II или III', isSolution: true, className: '8', code: 'C5', kemler: '80', packingGroup: 'II или III', labels: ['8'], card: '809', identitySources: [RPOHV_NAOH, ICSC_NAOH], profileSource: ICSC_NAOH,
    main: ['Водный раствор сильного основания.', 'При разбавлении выделяется значительное количество тепла.', 'Плотность и другие свойства раствора зависят от концентрации и без неё не публикуются.'], fire: ['Не горит.', 'Реагирует с кислотами.', 'Воздействует на алюминий, олово, свинец и цинк с выделением горючего водорода.'], health: ['Вызывает тяжёлые ожоги кожи и серьёзное повреждение глаз.', 'Аэрозоль опасен для дыхательных путей.', 'Опасен при проглатывании.'], routes: ['вдыхание аэрозоля', 'проглатывание', 'кожа', 'глаза'], ppe: ['Химически стойкая защитная одежда и перчатки.', 'Защита глаз и лица.', 'При опасной концентрации аэрозоля — соответствующая защита органов дыхания.'], actions: ['Ограничить доступ.', 'Не касаться пролива без защиты.', 'Собрать в совместимую коррозионностойкую тару.', 'Не допускать попадания в окружающую среду.'], operation: 'collection', response: ['Собрать инертным материалом в закрываемую совместимую тару.', 'Химическую нейтрализацию проводить только по утверждённому регламенту с контролем температуры и pH.'], firstAid: ['При вдыхании аэрозоля — свежий воздух и немедленная медицинская помощь.', 'Кожу промывать водой не менее 15 минут и снять загрязнённую одежду.', 'Глаза промывать водой и немедленно обратиться за медицинской помощью.', 'При проглатывании не вызывать рвоту.'], flags: { isCryogenic: false, isToxicGas: false, isCorrosive: true, isOxidizer: false, isFlammable: false, isExplosive: false, isWaterReactive: true, isEnvironmentalHazard: true, isAsphyxiant: false } }),
  pilot({ un: '1972', recordId: 'un1972-methane-refrigerated-liquid', name: 'Метан охлаждённый жидкий', chemicalName: 'Метан', cas: '74-82-8', formula: 'CH₄', aliases: ['Газ природный охлаждённый жидкий с высоким содержанием метана'], physicalForm: 'Охлаждённая сжиженная жидкость', concentration: 'Метан либо природный газ с высоким содержанием метана', isRefrigeratedLiquid: true, className: '2.1', code: '3F', kemler: '223', packingGroup: '—', labels: ['2.1'], card: '204', identitySources: [ICSC_METHANE], profileSource: ICSC_METHANE,
    main: ['Бесцветная криогенная жидкость без запаха.', 'При испарении образует газ, который после прогрева легче воздуха.', 'Холодное плотное облако непосредственно после разлива может распространяться у поверхности до прогрева.'], fire: ['Чрезвычайно легковоспламеняющееся вещество.', 'Смеси газа с воздухом взрывоопасны.', 'Удалить все источники зажигания.'], health: ['Высокая концентрация вытесняет кислород и может вызвать удушье.', 'Контакт с жидкостью или холодным паром вызывает холодовое поражение и обморожение.'], routes: ['вдыхание', 'кожа', 'глаза'], ppe: ['Автономный дыхательный аппарат в кислорододефицитной атмосфере.', 'Холодоизолирующие перчатки.', 'Защита глаз и лица.'], actions: ['Эвакуировать опасную зону.', 'Удалить источники зажигания.', 'Обеспечить вентиляцию.', 'Не направлять струю воды на жидкий продукт.'], operation: 'no_neutralization', response: ['Химическая нейтрализация не применяется.', 'Безопасно перекрыть подачу и обеспечить контролируемое рассеивание.', 'Контролировать содержание кислорода и горючего газа.'], firstAid: ['При вдыхании — свежий воздух, покой, при необходимости искусственное дыхание и медицинская помощь.', 'При обморожении промывать водой, не снимать примерзшую одежду и обратиться за медицинской помощью.'], flags: { isCryogenic: true, isToxicGas: false, isCorrosive: false, isOxidizer: false, isFlammable: true, isExplosive: true, isWaterReactive: false, isEnvironmentalHazard: false, isAsphyxiant: true } }),
];

export function getValidatedSubstanceByUN(unNumber: string): ValidatedSubstanceRecord | undefined {
  const un = unNumber.replace(/\D/gu, '').padStart(4, '0');
  return VALIDATED_SUBSTANCES_PILOT.find((record) => record.transport.unNumber.value === un);
}
